void water_pump(void);
void water_for_5s(void);
void full_tank(void);
void empty_tank(void);
void input_config(void);
void read_pins(void);
void pump_config(void);
void read_level(void);
void pump(void);